cookie:
  expiry_days: 30
  key: cv_extractor_secret_key_2024
  name: cv_extractor_auth
credentials:
  usernames:
    admin:
      name: Administrator
      password: $2b$12$uJpFGyn1OEGR57KVDFh8VOVTGasAZCg4/bmTLaCjWkclQ1eCi3Ody
      role: admin
    cdinternationalprojekt@gmail.com:
      name: Cristian Dragoi
      password: $2b$12$1cgU5k4OteicwA.3wnWO.uczexPgJfoLwNzdM3zOZul.SF/QjA2u6
      role: admin
    cris:
      name: Cris
      password: $2b$12$rjcCiZVLb47BZE1pYpo5veppUzRIoS4PrPVNUkgJtP/XvZHl7kDda
      role: admin
